### ISSUE TITLE
The user intarface is too big for 1080p monitors.

### ISSUE THREAD

**Issue by paryska99** [RafaGago/artv-audio#1]
Altough you can resize the window down, the actual area which you need to grab (bottom right of the window) is out of screen because of the window size, making it really hard or impossible to downsize and use correctly.

Details:
VST3 
Waveform Free 64bit 
Windows 10

**Comment by RafaGago** [comment]
This commit should fix it:
https://github.com/RafaGago/artv-audio/commit/3170adff1f01e6bbf3dcbd33266a3b3fec9c344e

I uploaded to KVR. Otherwise the artifacts are here too:
https://github.com/RafaGago/artv-audio/actions/runs/998738851

Please, report back if this fixes the issue. Thanks for reporting!

**Comment by paryska99** [comment]
It does indeed fit on a hd resolution screen now.

Thank you for caring about the issue as the vst seems really solid!
